# Generated by Django 5.1.4 on 2025-01-12 06:34

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_customer', '0005_remove_user_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', ckeditor.fields.RichTextField()),
                ('A', ckeditor.fields.RichTextField()),
                ('B', ckeditor.fields.RichTextField()),
                ('C', ckeditor.fields.RichTextField()),
                ('D', ckeditor.fields.RichTextField()),
                ('answer', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=20)),
                ('score', models.PositiveIntegerField()),
                ('grade', models.CharField(choices=[('10', '10'), ('11', '11'), ('1', '1'), ('2', '2'), ('3', '3')], max_length=10)),
            ],
            options={
                'db_table': 'Quiz',
            },
        ),
        migrations.CreateModel(
            name='Science',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('duration_in_minutes', models.PositiveIntegerField(default=60)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'Science',
            },
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveIntegerField()),
                ('total_questions', models.PositiveIntegerField()),
                ('correct_answers', models.PositiveIntegerField()),
                ('attempt_number', models.PositiveIntegerField(default=1)),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField()),
                ('status', models.CharField(choices=[('passed', 'Passed'), ('failed', 'Failed')], default='failed', max_length=20)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='app_quiz.quiz')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='app_customer.student')),
                ('science', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='app_quiz.science')),
            ],
            options={
                'verbose_name': 'Result',
                'verbose_name_plural': 'Results',
                'db_table': 'Result',
                'ordering': ['-score'],
            },
        ),
        migrations.AddField(
            model_name='quiz',
            name='science',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app_quiz.science'),
        ),
    ]
