# Generated by Django 5.1.4 on 2025-01-12 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_quiz', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='score',
            field=models.FloatField(),
        ),
    ]
