# Generated by Django 5.1.4 on 2025-01-23 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_quiz', '0008_alter_result_status_exam'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pass_Exam_Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveIntegerField(default=300)),
            ],
        ),
    ]
