# Generated by Django 5.1.4 on 2025-01-11 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_customer', '0002_user_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='full_name_en',
        ),
        migrations.RemoveField(
            model_name='student',
            name='full_name_ru',
        ),
        migrations.RemoveField(
            model_name='student',
            name='full_name_uz',
        ),
    ]
