# Generated by Django 5.1.4 on 2025-01-11 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_customer', '0003_remove_student_full_name_en_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='districts',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='student',
            name='region',
            field=models.CharField(max_length=200),
        ),
    ]
