# Generated by Django 5.1.4 on 2025-01-12 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_customer', '0004_alter_student_districts_alter_student_region'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
    ]
