# Generated by Django 5.1.4 on 2025-01-18 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_customer', '0005_remove_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='academy_or_school',
            field=models.CharField(max_length=200),
        ),
    ]
